### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by WrRan** [WING-NUS/JD2Skills-BERT-XMLC#1]
Good work. 👍 
But I just found data in this repo, where is the code?

**Comment by knmnyn** [comment]
Thanks for your interest. @AKBakshay will be committing the code base for the XMLC soon. Apologies for the delay. We'll inform you when it's there.

**Comment by knmnyn** [comment]
Hi @WrRan , @AKBakshay has committed the code from the paper this past week.  Hope it is in good order!

**Comment by WrRan** [comment]
Many thanks!
