### ISSUE TITLE
Predicted skill label as model predict output instead metrice 

### ISSUE THREAD

**Issue by talk2jaydip** [WING-NUS/JD2Skills-BERT-XMLC#2]
How to get predicted skill label as model predicts output with.

currently it showing this as predict output
NDCG@5: 36.2208292638756
NDCG@10: 52.89963620027874
NDCG@30: 79.06685233102785
NDCG@50: 83.86957177663294
NDCG@100: 87.03881424152917
Recall@5: 21.236956407627584
Recall@10: 39.58334077230501
Recall@30: 77.80641234792749
Recall@50: 86.75905363696252
Recall@100: 93.56779238774804
EIM: 115.88814640810699
RIIM: 64.6082733676545
REIM: 25.730109648276965

Is there a way to get predicted label ?

**Comment by Josh1108** [comment]
Yes, you can do this by editing the Metrics file and print the skills there for validation/ testing. Seems like the authors referred to 

https://github.com/lonePatient/Bert-Multi-Label-Text-Classification, you can do the same for more information.

**Comment by AKBakshay** [comment]
Thank you @talk2jaydip for your comment. 

In the recent commit, I have added functionality to directly output the skill labels by specifying "predict_labels" and "predict_idx" arguments.

**Comment by talk2jaydip** [comment]
Thanks
