### ISSUE TITLE
How to prepare custom test dataset

### ISSUE THREAD

**Issue by talk2jaydip** [WING-NUS/JD2Skills-BERT-XMLC#3]
Current pickle datasets have JD and label with dimension (2548), is there a way to create custom test  dataset for given JD ?

**Comment by AKBakshay** [comment]
Model could be tested with any dataset, given that it's properly formatted.  You can change the predicted vector dimensions by replacing the last fc layer with another layer of required dimensions.

**Comment by yazidoxx** [comment]
Can you please mention the format of the custom dataset  I mean how it should be ??
