### ISSUE TITLE
Prediction is from the untrained model

### ISSUE THREAD

**Issue by Josh1108** [WING-NUS/JD2Skills-BERT-XMLC#4]
in the testing phase, run_bert currently loads the base model instead of the checkpoint. This line should be changed to 

`model = BertForMultiLable.from_pretrained(config['checkpoint_dir'], num_labels=len(label_list))`

for testing.

**Comment by AKBakshay** [comment]
Thank you @Josh1108  for pointing it out. 

By default, it is set to run the test on the pre-trained model weighs. For checkpoints, it could be configured with "checkpoint_dir".

In the recent commit, an additional "test_path" argument is added to specify the weights for testing.
