### ISSUE TITLE
Cannot reproduce results quoted in paper

### ISSUE THREAD

**Issue by Josh1108** [WING-NUS/JD2Skills-BERT-XMLC#5]
I'm sure I'm doing something wrong. I am reproducing the results by training the model from scratch using the preprocessed dataset provided. I've used 11 epochs and the rest of my hyperparameters are the defaults in the repository. I used the `pybert/model_setup/CAB_dataset_script.py` script to generate extra training examples.

I'm getting recall@5 as 15.27 and the other metrics are correspondingly a bit lower as well. Is there something that I'm missing? 

Are there any other parameters I need to take care of?

**Comment by knmnyn** [comment]
Hi @AKBakshay can you look at @Josh1108 's problem with replication?  Thanks!

**Comment by AKBakshay** [comment]
Hi @Josh1108. It is difficult to state the reason for the mismatch in results with insufficient details. Kindly, check if the training setup is correct and have a look at logs if there is some issue while training.
